import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { toast } from 'sonner';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Card, CardBody, CardHeader } from '../components/ui/Card';
import { PageHeader } from '../components/ui/PageHeader';
import { Button } from '../components/ui/Button';
import { Field, Select, TextInput, Toggle } from '../components/ui/Field';
import { Badge } from '../components/ui/Badge';
import { Notice } from '../components/ui/States';
import { createPatient, getNextPatientId } from '../api/patients';

interface FormState {
  fullName:  string;
  dob:       string;
  gender:    string;
  phone:     string;
  email:     string;
  fhirId:    string;
  ehrSystem: string;
}

const initialForm: FormState = {
  fullName:  '',
  dob:       '',
  gender:    '',
  phone:     '',
  email:     '',
  fhirId:    '',
  ehrSystem: 'Epic',
};

export function AddPatient() {
  const navigate     = useNavigate();
  const queryClient  = useQueryClient();

  const [form,    setForm]    = useState<FormState>(initialForm);
  const [errors,  setErrors]  = useState<Partial<Record<keyof FormState | 'general', string>>>({});
  const [consent, setConsent] = useState({ ehr: true, wearable: false, ai: false });

  const update = (key: keyof FormState, value: string) =>
    setForm((prev) => ({ ...prev, [key]: value }));

  // ── Next patient ID (read-only preview) ──────────────────────────────────
  const { data: nextIdData } = useQuery({
    queryKey: ['patients-next-id'],
    queryFn:  getNextPatientId,
  });
  const displayId = nextIdData ?? '…';

  // ── Create patient mutation ───────────────────────────────────────────────
  const mutation = useMutation({
    mutationFn: () => createPatient({
      name:      form.fullName.trim(),
      dob:       form.dob,
      gender:    form.gender,
      phone:     form.phone || undefined,
      email:     form.email || undefined,
      fhirId:    form.fhirId.trim(),
      ehrSystem: form.ehrSystem,
      consents:  consent,
    }),
    onSuccess: (newPatient) => {
      // Invalidate patient list so it refreshes
      queryClient.invalidateQueries({ queryKey: ['patients'] });
      queryClient.invalidateQueries({ queryKey: ['patients-next-id'] });

      if (!consent.ai) {
        toast.warning('AI risk analysis consent not granted', {
          description: 'The patient will be onboarded without predictive risk scoring until consent is recorded.',
        });
      }
      toast.success('Patient saved', {
        description: `${form.fullName} registered and queued for FHIR synchronization.`,
      });
      navigate(`/patients/${newPatient.id}`);
    },
    onError: (error: unknown) => {
      const fieldErrors = extractFieldErrors(error);
      if (Object.keys(fieldErrors).length > 0) {
        setErrors(fieldErrors);
      } else {
        const msg = extractGeneralMessage(error);
        setErrors({ general: msg });
        toast.error('Failed to save patient', { description: msg });
      }
    },
  });

  // ── Client-side validation ────────────────────────────────────────────────
  const validate = (): boolean => {
    const next: Partial<Record<keyof FormState, string>> = {};
    if (!form.fullName.trim()) next.fullName = 'Full name is required.';
    if (!form.dob)             next.dob      = 'Date of birth is required for identity matching.';
    if (!form.gender)          next.gender   = 'Select the recorded gender.';
    if (!form.fhirId.trim())   next.fhirId   = 'FHIR Patient ID is required to establish the twin.';
    setErrors(next);
    return Object.keys(next).length === 0;
  };

  const submit = (event: React.FormEvent) => {
    event.preventDefault();
    if (!validate()) return;
    mutation.mutate();
  };

  const submitting = mutation.isPending;

  return (
    <div className="mx-auto max-w-4xl">
      <PageHeader
        title="Add patient"
        subtitle="Register a patient, connect their EHR record and capture the consents required before any AI analysis."
        backTo={{ to: '/patients', label: 'Back to patients' }}
      />

      {errors.general && (
        <Notice tone="critical" title="Unable to save patient">
          {errors.general}
        </Notice>
      )}

      <form onSubmit={submit} noValidate className="mt-4 space-y-4">
        <Card>
          <CardHeader title="Patient information" description="Identity details used for record matching" />
          <CardBody className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <Field label="Patient ID" htmlFor="patientId" hint="Auto-generated by MediSphere">
              <TextInput id="patientId" value={displayId} readOnly className="bg-slate-50 text-slate-500" />
            </Field>
            <Field label="Full name" htmlFor="fullName" required error={errors.fullName}>
              <TextInput
                id="fullName" value={form.fullName}
                onChange={(e) => update('fullName', e.target.value)}
                invalid={Boolean(errors.fullName)} placeholder="e.g. Aaron Whitfield"
              />
            </Field>
            <Field label="Date of birth" htmlFor="dob" required error={errors.dob}>
              <TextInput
                id="dob" type="date" value={form.dob}
                onChange={(e) => update('dob', e.target.value)}
                invalid={Boolean(errors.dob)}
              />
            </Field>
            <Field label="Gender" htmlFor="gender" required error={errors.gender}>
              <Select
                id="gender" value={form.gender}
                onChange={(e) => update('gender', e.target.value)}
                invalid={Boolean(errors.gender)}
              >
                <option value="">Select…</option>
                <option>Female</option>
                <option>Male</option>
                <option>Other</option>
                <option>Prefer not to say</option>
              </Select>
            </Field>
            <Field label="Contact phone" htmlFor="phone">
              <TextInput
                id="phone" value={form.phone}
                onChange={(e) => update('phone', e.target.value)}
                placeholder="+1 (415) 555-0000"
              />
            </Field>
            <Field label="Contact email" htmlFor="email">
              <TextInput
                id="email" type="email" value={form.email}
                onChange={(e) => update('email', e.target.value)}
                placeholder="patient@example.com"
              />
            </Field>
          </CardBody>
        </Card>

        <Card>
          <CardHeader title="Healthcare integration" description="FHIR R4 · SMART on FHIR authorization" />
          <CardBody className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <Field
              label="FHIR Patient ID" htmlFor="fhirId" required error={errors.fhirId}
              hint="Resource identifier from the source EHR"
            >
              <TextInput
                id="fhirId" value={form.fhirId}
                onChange={(e) => update('fhirId', e.target.value)}
                invalid={Boolean(errors.fhirId)} placeholder="fhir:Patient/0000-0000"
              />
            </Field>
            <Field label="EHR system" htmlFor="ehrSystem">
              <Select id="ehrSystem" value={form.ehrSystem} onChange={(e) => update('ehrSystem', e.target.value)}>
                <option>Epic</option>
                <option>Cerner</option>
                <option>Allscripts</option>
                <option>MEDITECH</option>
              </Select>
            </Field>
            <div className="sm:col-span-2">
              <p className="mb-1.5 text-xs font-medium text-slate-700">FHIR connection status</p>
              <div className="flex items-center gap-3 rounded-md border border-slate-200 bg-slate-50 px-3 py-2.5">
                <Badge tone={form.fhirId ? 'healthy' : 'neutral'} dot>
                  {form.fhirId ? 'Ready to connect' : 'Not connected'}
                </Badge>
                <p className="text-xs text-slate-500">
                  {form.fhirId
                    ? 'Connection will be validated against the source system when the patient is saved.'
                    : 'Enter a FHIR Patient ID to validate the connection.'}
                </p>
              </div>
            </div>
          </CardBody>
        </Card>

        <Card>
          <CardHeader title="Consent" description="Consent must be recorded before the corresponding data is ingested or analysed" />
          <CardBody className="pt-0">
            <Toggle
              id="consent-ehr" checked={consent.ehr}
              onChange={(v) => setConsent((c) => ({ ...c, ehr: v }))}
              label="EHR data access"
              description="Permits retrieval of conditions, medications and encounters via FHIR."
            />
            <Toggle
              id="consent-wearable" checked={consent.wearable}
              onChange={(v) => setConsent((c) => ({ ...c, wearable: v }))}
              label="Wearable data access"
              description="Permits continuous vitals streaming into the Kafka pipeline."
            />
            <Toggle
              id="consent-ai" checked={consent.ai}
              onChange={(v) => setConsent((c) => ({ ...c, ai: v }))}
              label="AI risk analysis"
              description="Permits privacy-preserving federated risk prediction on this patient's twin."
            />
            {!consent.ai && (
              <div className="mt-3">
                <Notice tone="warning" title="AI risk analysis consent not granted">
                  Predictions and AI care-plan generation will remain unavailable for this patient until consent is recorded.
                </Notice>
              </div>
            )}
          </CardBody>
        </Card>

        <div className="flex flex-wrap justify-end gap-2 pb-4">
          <Button type="button" onClick={() => navigate('/patients')} disabled={submitting}>
            Cancel
          </Button>
          <Button type="submit" variant="primary" disabled={submitting}>
            {submitting ? 'Saving…' : 'Save patient'}
          </Button>
        </div>
      </form>
    </div>
  );
}

// ── Error helpers ─────────────────────────────────────────────────────────

function extractFieldErrors(error: unknown): Partial<Record<string, string>> {
  if (!error || typeof error !== 'object') return {};
  const e = error as { response?: { data?: { fieldErrors?: Record<string, string> } } };
  return e.response?.data?.fieldErrors ?? {};
}

function extractGeneralMessage(error: unknown): string {
  if (!error || typeof error !== 'object') return 'An unexpected error occurred.';
  const e = error as { response?: { status?: number; data?: { message?: string } } };
  const status = e.response?.status;
  if (status === 409) return e.response?.data?.message ?? 'A patient with this FHIR ID already exists.';
  if (status === 400) return e.response?.data?.message ?? 'Please check your input and try again.';
  if (status && status >= 500) return 'Server error — please try again.';
  return 'Unable to save the patient. Please check your connection.';
}
