import { useEffect, useState } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { toast } from 'sonner';
import { RefreshCwIcon, SparklesIcon } from 'lucide-react';
import { PageHeader } from '../components/ui/PageHeader';
import { Card, CardBody, CardHeader, DefinitionRow } from '../components/ui/Card';
import { Badge } from '../components/ui/Badge';
import { Button } from '../components/ui/Button';
import { AiNotice, DemoDataNote } from '../components/ui/AiNotice';
import { EmptyState, SkeletonBlock } from '../components/ui/States';
import { Select } from '../components/ui/Field';
import { getPatient, getPatients } from '../api/patients';
import { generateCarePlan, getCarePlan } from '../api/carePlans';
import type { CarePlan } from '../schemas/carePlan.schema';

/**
 * CarePlanGenerator — Phase 6 wiring.
 *
 * Create mode  (/care-plans/new?patientId=P001):
 *   - Loads patient via getPatient(patientId)
 *   - Calls generateCarePlan(patientId) on mount
 *   - "Review plan" navigates to /care-plans/:newPlanId/review using real API plan ID
 *   - "Regenerate" calls generateCarePlan(patientId) again
 *
 * Edit mode (/care-plans/:planId/edit):
 *   - Loads plan via getCarePlan(planId)
 *   - Populates recommendation display from real plan
 *   - "Review plan" navigates to /care-plans/:planId/review
 *
 * Shows EmptyState when neither patientId nor planId is present.
 *
 * UI layout, colors, typography and component structure unchanged.
 */
export function CarePlanGenerator() {
  const navigate = useNavigate();
  const queryClient = useQueryClient();
  const { planId } = useParams<{ planId: string }>();
  const [searchParams] = useSearchParams();
  const patientId = searchParams.get('patientId');
  const [selectedPatientId, setSelectedPatientId] = useState('');

  const isEditMode   = Boolean(planId);
  const isCreateMode = !isEditMode && Boolean(patientId);

  // The generated/loaded plan
  const [currentPlan, setCurrentPlan] = useState<CarePlan | null>(null);

  // ── Load patients when the generator is opened without a patient context ──
  const { data: patientsPage, isLoading: patientsLoading } = useQuery({
    queryKey: ['patients', {}, 0, 100],
    queryFn: () => getPatients({}, 0, 100),
    enabled: !isEditMode && !patientId,
    staleTime: 2 * 60 * 1000,
  });

  // ── Load patient (create mode) ────────────────────────────────────────
  const { data: patient, isLoading: patientLoading } = useQuery({
    queryKey: ['patient', patientId],
    queryFn:  () => getPatient(patientId!),
    enabled:  isCreateMode && Boolean(patientId),
  });

  // ── Load existing plan (edit mode) ────────────────────────────────────
  const { data: existingPlan, isLoading: planLoading } = useQuery({
    queryKey: ['care-plan', planId],
    queryFn:  () => getCarePlan(planId!),
    enabled:  isEditMode && Boolean(planId),
  });

  // Sync existing plan into state when edit mode loads
  useEffect(() => {
    if (existingPlan) setCurrentPlan(existingPlan);
  }, [existingPlan]);

  // ── Generate mutation ─────────────────────────────────────────────────
  const { mutate: generate, isPending: generating } = useMutation({
    mutationFn: () => generateCarePlan(patientId!),
    onSuccess: (plan) => {
      setCurrentPlan(plan);
      queryClient.invalidateQueries({ queryKey: ['care-plans'] });
      toast.success('Care plan generated', {
        description: `Draft plan ${plan.id} created from AI stub. Goal: ${plan.goal}`,
      });
    },
    onError: () => {
      toast.error('Generation failed', {
        description: 'Could not generate a care plan. Please try again.',
      });
    },
  });

  // Run generation automatically on mount in create mode
  const [autoGenerated, setAutoGenerated] = useState(false);
  useEffect(() => {
    if (isCreateMode && !autoGenerated && !generating) {
      setAutoGenerated(true);
      generate();
    }
  }, [isCreateMode, autoGenerated, generating, generate]);

  // ── Empty state — no context ──────────────────────────────────────────
  if (!isEditMode && !isCreateMode) {
    const patients = patientsPage?.content ?? [];

    return (
      <div>
        <PageHeader
          title="Generate personalized care plan"
          subtitle="AI-assisted care plan generation"
          backTo={{ to: '/care-plans', label: 'Back to care plans' }}
        />
        <EmptyState
          title="No patient selected"
          description="Select a patient to generate a care plan."
          action={
            <div className="flex flex-col items-stretch gap-2 sm:flex-row sm:items-center">
              <Select
                id="care-plan-patient"
                value={selectedPatientId}
                onChange={(e) => setSelectedPatientId(e.target.value)}
                className="w-64"
                disabled={patientsLoading}
              >
                <option value="">{patientsLoading ? 'Loading patients…' : 'Select patient'}</option>
                {patients.map((p) => (
                  <option key={p.id} value={p.id}>{p.name} ({p.id})</option>
                ))}
              </Select>
              <Button
                variant="primary"
                disabled={!selectedPatientId}
                onClick={() => navigate(`/care-plans/new?patientId=${selectedPatientId}`)}
              >
                Continue
              </Button>
            </div>
          }
        />
      </div>
    );
  }

  const isLoading = isCreateMode ? patientLoading || generating : planLoading;

  // Derive display values from real data
  const plan         = currentPlan ?? existingPlan ?? null;
  const displayName  = isEditMode
    ? (plan?.patientName ?? `Plan ${planId}`)
    : (patient?.name ?? patientId ?? '');
  const contextLabel = isEditMode
    ? `Edit care plan ${planId}`
    : `Patient ${displayName}`;

  // CVD risk and condition badges derived from the plan (or patient predictions in future phases)
  const riskBadgeTone = plan?.riskLevel === 'High' ? 'critical'
    : plan?.riskLevel === 'Medium' ? 'warning' : 'info';

  // Review target uses real plan ID from API response
  const reviewTarget = plan
    ? `/care-plans/${plan.id}/review`
    : isEditMode
      ? `/care-plans/${planId}/review`
      : '/care-plans';

  const recommendations = plan?.recommendations ?? [];

  return (
    <div>
      <PageHeader
        title={isEditMode ? 'Edit care plan' : 'Generate personalized care plan'}
        subtitle={`${contextLabel} · derived from the current Digital Health Twin, AI risk output and institutional clinical guidelines`}
        backTo={{ to: '/care-plans', label: 'Back to care plans' }}
        meta={
          plan ? (
            <>
              {plan.riskLevel && (
                <Badge tone={riskBadgeTone}>{plan.riskLevel} risk</Badge>
              )}
              {plan.goal && <Badge tone="info">Goal: {plan.goal}</Badge>}
            </>
          ) : undefined
        }
        actions={
          <>
            <Button onClick={() => navigate('/care-plans')}>Cancel</Button>
            {isCreateMode && (
              <Button onClick={() => generate()} disabled={generating}>
                <RefreshCwIcon className={`h-4 w-4 ${generating ? 'animate-spin' : ''}`} aria-hidden="true" />
                Regenerate
              </Button>
            )}
            <Button
              variant="primary"
              onClick={() => navigate(reviewTarget)}
              disabled={!plan}
            >
              Review plan
            </Button>
          </>
        }
      />

      <div className="mb-4">
        <AiNotice kind="carePlan" />
      </div>

      <div className="grid grid-cols-1 gap-4 xl:grid-cols-4">
        {/* Clinical inputs panel */}
        <Card className="xl:col-span-1">
          <CardHeader title="Clinical inputs" icon={<SparklesIcon className="h-4 w-4" />} />
          <CardBody className="pt-0">
            {isLoading || !plan ? (
              <div className="space-y-2">
                <SkeletonBlock className="h-4 w-full" />
                <SkeletonBlock className="h-4 w-3/4" />
                <SkeletonBlock className="h-4 w-2/3" />
              </div>
            ) : (
              <dl>
                <DefinitionRow label="Patient"    value={plan.patientName} />
                <DefinitionRow label="Risk level" value={<span className={plan.riskLevel === 'High' ? 'text-critical-600' : 'text-amber-600'}>{plan.riskLevel}</span>} />
                <DefinitionRow label="Health goal" value={plan.goal} />
                {plan.predictedOutcome && (
                  <>
                    <DefinitionRow
                      label="Current risk"
                      value={`${plan.predictedOutcome.before}${plan.predictedOutcome.unit}`}
                    />
                    <DefinitionRow
                      label="Projected after"
                      value={<span className="text-teal-700">{plan.predictedOutcome.after}{plan.predictedOutcome.unit}</span>}
                    />
                  </>
                )}
                <DefinitionRow label="Generated by" value={plan.generatedBy} />
              </dl>
            )}
            <DemoDataNote className="mt-3" />
          </CardBody>
        </Card>

        {/* Recommendations panel */}
        <div className="space-y-3 xl:col-span-3">
          {isLoading ? (
            Array.from({ length: 4 }).map((_, i) => (
              <SkeletonBlock key={i} className="h-40" />
            ))
          ) : recommendations.length === 0 ? (
            <Card>
              <CardBody>
                <p className="text-sm text-slate-500">
                  {generating ? 'Generating recommendations…' : 'No recommendations yet.'}
                </p>
              </CardBody>
            </Card>
          ) : (
            recommendations.map((rec, index) => (
              <Card key={rec.id}>
                <CardHeader
                  title={
                    <span className="flex items-center gap-2">
                      <span className="flex h-5 w-5 items-center justify-center rounded bg-slate-100 text-2xs font-semibold text-slate-600">
                        {index + 1}
                      </span>
                      {rec.title}
                    </span>
                  }
                  description={rec.evidence}
                  actions={<Badge tone="info">AI recommendation</Badge>}
                />
                <CardBody className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-4">
                  <Detail label="Goal"            value={rec.goal} />
                  <Detail label="Intervention"    value={rec.intervention} />
                  <Detail label="Monitoring"      value={rec.monitoring} />
                  <Detail label="Expected outcome" value={rec.outcome} />
                </CardBody>
              </Card>
            ))
          )}

          <Card>
            <CardBody className="flex flex-col items-start justify-between gap-3 sm:flex-row sm:items-center">
              <p className="text-sm text-slate-600">
                These are AI-generated suggestions. A provider must review, modify or reject each recommendation
                before it becomes an active plan.
              </p>
              <div className="flex shrink-0 gap-2">
                <Button onClick={() => navigate('/care-plans')}>Cancel</Button>
                <Button
                  variant="primary"
                  onClick={() => navigate(reviewTarget)}
                  disabled={!plan}
                >
                  Review plan
                </Button>
              </div>
            </CardBody>
          </Card>
        </div>
      </div>
    </div>
  );
}

function Detail({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <p className="text-2xs font-semibold uppercase tracking-wide text-slate-500">{label}</p>
      <p className="mt-1 text-sm leading-relaxed text-slate-700">{value}</p>
    </div>
  );
}
