package com.medisphere.domain;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.index.CompoundIndex;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.Instant;
import java.util.List;

/**
 * Patient document — persisted to MongoDB collection: patients
 *
 * Text index on name + fhirId enables full-text search.
 * Hard deletes are prohibited; use status = Inactive instead.
 */
@Document(collection = "patients")
@CompoundIndex(name = "text_search_idx", def = "{'name': 'text', 'fhirId': 'text'}")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Patient {

    /** Format: P001, P002, P003 … generated by PatientIdGenerator */
    @Id
    private String id;

    /** FHIR resource identifier from the source EHR (e.g. fhir:Patient/8a21-4c77) */
    @Indexed
    private String fhirId;

    private String name;

    private String dob;              // ISO-8601 date: 1968-04-12

    private String gender;           // Male | Female | Other | Prefer not to say

    private ContactInfo contact;

    private List<String> conditions;

    @Indexed
    @Builder.Default
    private String riskLevel = "Low";     // High | Medium | Low (updated by prediction service in Phase 4)

    @Indexed
    @Builder.Default
    private String status = "Active";     // Active | Inactive | Pending Consent

    @Indexed
    private String providerId;

    private String providerName;

    /** ID of this patient's digital health twin (HT-001, HT-002 …) */
    private String twinId;

    /** ID of this patient's consent document */
    private String consentId;

    private String ehrSystem;

    @Builder.Default
    private boolean fhirConnected = false;

    /** Overall wearable device status derived from wearable_devices collection */
    @Builder.Default
    private String wearableStatus = "Offline"; // Online | Offline

    @Builder.Default
    private boolean consentComplete = false;

    /** Last known health status text (updated by clinical workflows) */
    @Builder.Default
    private String healthStatus = "Pending review";

    /** Overall care-plan adherence 0–100 (updated by adherence service in Phase 6) */
    @Builder.Default
    private int adherence = 0;

    @CreatedDate
    private Instant createdAt;

    @LastModifiedDate
    private Instant updatedAt;

    // ── Embedded types ─────────────────────────────────────────────────────

    @Data
    @Builder
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ContactInfo {
        private String phone;
        private String email;
    }
}
